// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe05LjYs_6-HGdfUhsK0E2tlptUt1ZZTc',
    appId: '1:962159140975:web:1a1cc4447dcd0d4f96ed9a',
    messagingSenderId: '962159140975',
    projectId: 'daily-habits-32eac',
    authDomain: 'daily-habits-32eac.firebaseapp.com',
    storageBucket: 'daily-habits-32eac.firebasestorage.app',
    measurementId: 'G-Z3JLGQR780',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzEJVItB0FOi4pRwxjELN-VznQvOFd9q0',
    appId: '1:962159140975:android:f361a8e27c01df9a96ed9a',
    messagingSenderId: '962159140975',
    projectId: 'daily-habits-32eac',
    storageBucket: 'daily-habits-32eac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaWfbk9ndy_RNXgGLy34_7ZrgJ39S7zuw',
    appId: '1:962159140975:ios:003e8a20338470d296ed9a',
    messagingSenderId: '962159140975',
    projectId: 'daily-habits-32eac',
    storageBucket: 'daily-habits-32eac.firebasestorage.app',
    iosBundleId: 'com.daily.habits.dailyHabits',
  );

}